### PR TITLE
Adding support for Firewalls and little fixes

### LINKED ISSUE #9: Adding support for Firewalls and little fixes
Dear Shon,

I've added to your library the support for Firewall objects and adding droplet to firewall. I've also fixed a bug in `Collection.all()` method (not so serious, it will submit a request to a non-existing page. I've also configured this repository to work inside [Travis CI](https://travis-ci.org/) and [Coveralls](https://coveralls.io/). I've also fixed the code with `autopep` in order to be `PEP8` compliant.

I will submit such changes in a new pull request

### PR DESCRIPTION
**Pull request by bunop**
Closes #9. In details:
- passing flake8 tests
- Fixing flake8 issues using autopep8: re-written code in order to be `PEP8` compliant
- Testing firewalls objects
- Adding Firewall objects
- Bump version: 0.8 → 0.9.0.dev0 - managing versions with [bumpversion](https://pypi.org/project/bumpversion/) which is a python package which can manage code version
- refactoring `APIObject.send_req` method: I've simplified this method in order to add firewall objects (which replies with 204 - No content to a `POST` method). Now it will be more generic
- Adding travis CI setup scripts: I've added a tox file to test against Python `3.4`, `3.5`, `3.6`. I don't know is `3.7` is currently supported or not. [flake8](http://flake8.pycqa.org/en/latest/) will check that python code is compliant to [PEP8](https://www.python.org/dev/peps/pep-0008/) style
- Fixing tests
- Working with test_dosa_image_by_search test: I fixed a test that fails in master branch
- Asserting a bug in dosa.Collection.all() method: I wrote down a test to show that `Collection.all()` send a more request that required.

I hope that Travis CI will work, I see some momentary issues on CI. I don't know how this PR will be displayed without having set Travis CI and coverall. If you need to inspect those result, please take a look at: 
- https://travis-ci.org/bunop/dosa/builds/514748190
- https://coveralls.io/builds/22553032

### CODE REVIEW

**Comment by shon** [comment]
Thanks @bunop. I will take a look

**Comment by shon** [comment]
@bunop Thanks for your tremendous contribution.
Out of curiosity: Are you actively using dosa? What's your use case?

**Comment by bunop** [comment]
Thank you for your attention, shon. I discovered dosa while I was searching a library able to manage droplets in DO. I don't use DO intensively at the moment, for now I need to discover if I can move the processes we usually do in our institution in this cloud, and if this will be easy or not. My typical use case with dosa is to create a set of droplets automatically in order to apply Ansible recipies to set up my developing environment. I added the firewall functionality since after creating droplet, I need to add it manually.

**Comment by shon** [comment]
@bunop I am merging the changes. I will do some minor changes such as CI config and requirement versions etc after merge. 
Thanks again :)

**Pull request merged**
